# Generated by Django 5.0.4 on 2024-08-04 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_ransomware', '0003_remove_email_user_remove_networkpacket_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupdata',
            old_name='backup_time',
            new_name='backup_at',
        ),
        migrations.AddField(
            model_name='emailfilter',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficcapture',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailfilter',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailfilter',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trafficcapture',
            name='protocol',
            field=models.CharField(max_length=20),
        ),
    ]
